version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/data:/usr/src/app/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
